In [1]:
from lowGait import *

Program started
Connected to remote API server


In [3]:
initPos = np.zeros((6, 3))
for i in range(6):
    _,initPos[i] = vrep.simxGetObjectPosition(clientID, S1[i], BCS, vrep.simx_opmode_oneshot_wait)
initPos

array([[ 0.43498528,  0.32366395, -0.83543569],
       [-0.00213259,  0.77135247, -0.90852302],
       [-0.66730428,  0.38386053, -0.90989435],
       [ 0.66613156, -0.3871991 , -0.90922141],
       [-0.00196609, -0.77023238, -0.90961039],
       [-0.66658449, -0.38480085, -0.91010451]])

In [4]:
initPos[0]+=np.array([0.03696766, 0.16653222, 0.07867533])
closeLoopSetPos(initPos)

[[0.03731271 0.167512   0.07916337]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
bbb
[ 0.03071865  0.01095994 -0.03776863]
[[ 0.01316151 -0.0525856  -0.03401315]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
bbb
[-0.00361972 -0.00347491  0.00961223]
[[ 0.         -0.00548282 -0.00966275]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]


In [12]:
for i in range(1,19):
    vrep.simxSetJointTargetPosition(clientID, pole[i], 0.3, vrep.simx_opmode_oneshot_wait)

In [2]:
setleglength(0,[0.10269773, 0.14291108, 0.126908])
a = llc.querry(np.array([0.10269773, 0.14291108, 0.126908,0.03696766, 0.16653222, 0.07867533]),0)
a

array([ 0.03039853,  0.01102045, -0.03751147], dtype=float32)

In [3]:
getleglength(0)

array([0.0693754 , 0.07032102, 0.07020676])

In [16]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5417943000793457, 0.31277674436569214, -0.7302080392837524])

In [17]:
setleglength(0,np.array([0.07,0.07,0.07])+a)

In [18]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5527091026306152, 0.3218441307544708, -0.7179738283157349])

In [4]:
import pickle as pkl

In [5]:
with open("data3.pkl","rb") as f:
    data = pkl.load(f)


In [13]:
data["dls"][2]

array([ 0.02081359,  0.01358641, -0.02911045])

In [12]:
a = llc.querry(np.array([0.10269773, 0.14291108, 0.126908,0.03696766, 0.16653222, 0.07867533]),0)
a

array([ 0.03039853,  0.01102045, -0.03751147], dtype=float32)