In [1]:
from lowGait import *

Program started
Connected to remote API server


In [2]:
initPos = np.zeros((6, 3))
for i in range(6):
    _,initPos[i] = vrep.simxGetObjectPosition(clientID, S1[i], BCS, vrep.simx_opmode_oneshot_wait)
initPos

array([[ 0.53662699,  0.29692054, -0.73799765],
       [ 0.02599293,  0.77073056, -0.9065696 ],
       [-0.64931446,  0.40522689, -0.91204554],
       [ 0.65335846, -0.40947056, -0.90644509],
       [-0.0292604 , -0.76459366, -0.91209799],
       [-0.67426819, -0.35351145, -0.91515201]])

In [3]:
initPos[0][2]+=0.006
closeLoopSetPos(initPos)

[[0.         0.         0.00596036]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[ 4.2116804e-05 -2.8352675e-04  1.1464487e-04]
[[0.         0.         0.00755729]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[ 4.2288015e-05 -2.8389221e-04  1.1478046e-04]
[[ 0.00542402  0.          0.00887402]
 [ 0.00698358  0.          0.        ]
 [ 0.          0.00767732  0.        ]
 [ 0.         -0.00812399  0.        ]
 [-0.00949377  0.          0.        ]
 [-0.00679165  0.00703937  0.        ]]
[ 4.1476913e-05 -2.8592179e-04  1.1761053e-04]
[[ 0.00772858  0.          0.00998862]
 [ 0.01167119  0.          0.        ]
 [ 0.          0.01224169  0.        ]
 [-0.00562423 -0.01219195  0.        ]
 [-0.01396483  0.          0.     

KeyboardInterrupt: 

In [54]:
for i in range(1,19):
    vrep.simxSetJointTargetPosition(clientID, pole[i], 0.3, vrep.simx_opmode_oneshot_wait)

In [6]:
setleglength(0,[0.07,0.07,0.07])
a = llc.querry(np.array([0.07,0.07,0.07,0,0,0.05]),0)
a

array([ 4.1087518e-05, -2.7917809e-04,  1.0775733e-04], dtype=float32)

In [5]:
getleglength(0)

array([0.06944126, 0.07035196, 0.07036233])

In [56]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5417264699935913, 0.3127991259098053, -0.730209469795227])

In [57]:
setleglength(0,np.array([0.07,0.07,0.07])+a)

In [58]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.542742133140564, 0.3115747570991516, -0.7300674915313721])

In [7]:
import pickle as pkl

In [8]:
with open("data3.pkl","rb") as f:
    data = pkl.load(f)


In [26]:
data["dls"][1]

array([-0.00396281,  0.00378334,  0.00365811])

In [29]:
a = llc.querry(np.array([0.12306219, 0.12732667, 0.12293565, 0.01304686,  0.0032855 , -0.0027777]),0)
a

array([ 0.00072695, -0.00417222,  0.00186163], dtype=float32)