In [1]:
from lowGait import *

Program started
Connected to remote API server


In [2]:
initPos = np.zeros((6, 3))
for i in range(6):
    _,initPos[i] = vrep.simxGetObjectPosition(clientID, S1[i], BCS, vrep.simx_opmode_oneshot_wait)
initPos

array([[ 0.56914377,  0.32543671, -0.66947204],
       [ 0.02344456,  0.79898673, -0.8891021 ],
       [-0.66944742,  0.41362089, -0.89445251],
       [ 0.66589224, -0.41527498, -0.89724749],
       [-0.04401758, -0.78162575, -0.90262955],
       [-0.70620358, -0.34052092, -0.90121323]])

In [3]:
initPos[0]+=np.array([0.0,0,0.1])
closeLoopSetPos(initPos)

[[0.         0.         0.09941444]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[ 0.00752065 -0.01436647 -0.01267835]
[[-0.04550326 -0.01845306  0.04901592]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[-0.00478508 -0.00608323 -0.0059321 ]
[[-0.03690267 -0.01415187  0.05031136]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
[-0.00298418 -0.00638585 -0.00644043]
[[-0.02969611 -0.01229775  0.04959074]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0

In [2]:
for i in range(1,19):
    vrep.simxSetJointTargetPosition(clientID, pole[i], 0.2, vrep.simx_opmode_oneshot_wait)

In [2]:
setleglength(0,[0.10269773, 0.14291108, 0.126908])
a = llc.querry(np.array([0.10269773, 0.14291108, 0.126908,0.03696766, 0.16653222, 0.07867533]),0)
a

array([ 0.03039853,  0.01102045, -0.03751147], dtype=float32)

In [3]:
getleglength(0)

array([0.0693754 , 0.07032102, 0.07020676])

In [16]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5417943000793457, 0.31277674436569214, -0.7302080392837524])

In [10]:
setleglength(0,np.array([0.07,0.07,0.07])+a)

In [18]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5527091026306152, 0.3218441307544708, -0.7179738283157349])

In [4]:
import pickle as pkl

In [5]:
with open("data3.pkl","rb") as f:
    data = pkl.load(f)


In [13]:
data["dls"][2]

array([ 0.02081359,  0.01358641, -0.02911045])

In [12]:
a = llc.querry(np.array([0.10269773, 0.14291108, 0.126908,0.03696766, 0.16653222, 0.07867533]),0)
a

array([ 0.03039853,  0.01102045, -0.03751147], dtype=float32)

In [2]:
recover()
print("recovered")
walk_a_step()

Finished
Finished
Finished
Finished
recovered
Finished
Finished
Finished
Finished
Finished
Finished
Finished


KeyboardInterrupt: 

Finished
Finished
Finished
