In [1]:
from lowGait import *

Program started
Connected to remote API server


In [12]:
initPos = np.zeros((6, 3))
for i in range(6):
    _,initPos[i] = vrep.simxGetObjectPosition(clientID, S1[i], BCS, vrep.simx_opmode_oneshot_wait)
initPos

array([[ 6.65276110e-01,  3.83911729e-01, -9.11300540e-01],
       [-8.72313976e-05,  7.68159091e-01, -9.11150932e-01],
       [-6.65713787e-01,  3.84630620e-01, -9.10634398e-01],
       [ 6.65424585e-01, -3.84259582e-01, -9.11031067e-01],
       [ 1.66267157e-04, -7.69093454e-01, -9.10445750e-01],
       [-6.66324317e-01, -3.84483159e-01, -9.10165131e-01]])

In [13]:
initPos[0][2]+=0.01
closeLoopSetPos(initPos)

[[0.         0.         0.01007141]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]
[0.00037464 0.00885043 0.05084481]
[[-0.04219687  0.22949538  0.055304  ]
 [-0.2174392   0.07177263  0.04261231]
 [-0.15007752 -0.16364753  0.03130388]
 [ 0.14647466  0.14058465  0.03991485]
 [ 0.22333595 -0.0585258   0.03347903]
 [ 0.05764115 -0.21569046  0.03534061]]
[-0.01886992 -0.00010154  0.07664111]
[[ 0.03497726  0.74128067 -0.00651025]
 [-0.66654775  0.46311074 -0.0415051 ]
 [-0.74652499 -0.3441568  -0.04179007]
 [ 0.72834343  0.30641544 -0.01119912]
 [ 0.65325239 -0.50977474 -0.02846283]
 [-0.10814625 -0.82801792 -0.04102743]]
[-0.07105088 -0.02147467  0.10502484]
[[-0.02683359  0.71248895 -0.05538457]
 [-0.37165371  0.26377732  0.05034429]
 [-0.53474963 -0.32935804 -0.03842956]
 [ 0.83518472  0.42909557 -0.3085919 ]
 [ 0.73291978 -0.78087717 -0.21771896]
 [-0.07

KeyboardInterrupt: 

In [16]:
for i in range(1,19):
    vrep.simxSetJointTargetPosition(clientID, pole[i], 0.3, vrep.simx_opmode_oneshot_wait)

In [13]:
setleglength(0,[0.07,0.07,0.07])
a = llc.querry(np.array([0.07,0.07,0.07,0,0,0.05]),0)
a

array([ 0.00354266, -0.00151115, -0.00228052], dtype=float32)

In [5]:
getleglength(0)

array([0.06944126, 0.07035196, 0.07036233])

In [56]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.5417264699935913, 0.3127991259098053, -0.730209469795227])

In [57]:
setleglength(0,np.array([0.07,0.07,0.07])+a)

In [58]:
vrep.simxGetObjectPosition(clientID, S1[0], BCS, vrep.simx_opmode_oneshot_wait)

(0, [0.542742133140564, 0.3115747570991516, -0.7300674915313721])

In [4]:
import pickle as pkl

In [5]:
with open("data3.pkl","rb") as f:
    data = pkl.load(f)


In [11]:
data["dls"][2]

array([-0.00385329,  0.00365431,  0.00379227])

In [2]:
a = llc.querry(np.array([0.12306219, 0.12732667, 0.12293565, 0.01304686,  0.0032855 , -0.0027777]),0)
a

array([-0.00052183,  0.00177926,  0.00781027], dtype=float32)

In [10]:
a = llc.querry(np.array([0.11915421, 0.13110328, 0.12665039, -0.02278483, -0.01325038, -0.01629972]),0)
a

array([-0.00153708,  0.00298057,  0.00908595], dtype=float32)